Fix unwraps in Client
Infisical/sdk pull request #12
Opened 2024-01-13 08:40 UTC by rustaceanrob

**Feel free to edit any one of these**

In the initialization of a `Client` there is an `unwrap` that I am not sure what to do with besides maybe throwing a specific error to the user that something went wrong with the environment variables or project config.

I added an additional `unwrap_or` so the entire initialization of the client has default values, but this behavior might not be desired and can be removed if no `user_agent` should throw an error.

Lastly, if a lock can't be acquire on the `Mutex` then another thread is using it, and I think the behavior should be the cache does not change, and there is no error. (as opposed to the unwrap)

2024-01-16 10:06 UTC, DanielHougaard requested changes
Left a few comments, good work!

2024-01-16 10:06 UTC, DanielHougaard commented on crates/infisical/src/client/client.rs
> +        let settings = settings_input.unwrap(); // show an error to set the .env? Not actually sure how this throws
I would honestly say that it's alright for it to throw a panic here. This would happen during the client initialization, if no settings or invalid settings are passed. Since we can't return a normal error, a rust panic would be alright here. 

What do you think?

2024-01-17 04:11 UTC, rustaceanrob commented on crates/infisical/src/client/client.rs
> +        let settings = settings_input.unwrap(); // show an error to set the .env? Not actually sure how this throws
I think an `expect` could be a good option because the SDK bindings will show the panic message even in Swift, Kotlin, etc. With a short message it might help point the user in the right direction.

2024-01-17 04:15 UTC, rustaceanrob commented
I tried making an edit straight from github and screwed up the commit haha. Will make a new PR removing that function.

2024-01-17 04:15 UTC, closed without merging